### ISSUE TITLE
Cannot find 'h1-walk-v0' when making environment with gymnasium

### ISSUE THREAD

**Issue by liushaohuai5** [carlosferrazza/humanoid-bench#10]
gymnasium.error.NameNotFound: Environment `h1-walk` doesn't exist.

Ubuntu 20.04
Python 3.8
gymnasium 0.29.1
gym 0.15.7

**Comment by liushaohuai5** [comment]
Solved by adding 'import humanoid_bench'. Easy to forget this. Thanks~

**Comment by formoree** [comment]
Thanks. I have solved the same problem.
