### ISSUE TITLE
ValueError: Error: resource not found via provider or OS filesystem 

### ISSUE THREAD

**Issue by mdjadu** [carlosferrazza/humanoid-bench#12]
There is some issues with the reading of the paths from the function **`from_the_xml`** (`mujoco.MjModel.from_xml_path(self.fullpath)`)

`ValueError: Error: resource not found via provider or OS filesystem: '/path/to/the/humanoid-bench/humanoid_bench/assets/envs/../shadow_hand_submodel/assets/forearm_0.obj'`

FYI i have added "path to the" to not revel the true path

i can understand it a **`mujoco`** error but because of that we cant simulate this repo

**Comment by carlosferrazza** [comment]
Hi @mdjadu, what is the command that leads to this error, and what is your operating system? 

You could try cloning the repo again, and retry this. Some users have reported that on some OS there might be issues with the capitalization of the asset files (e.g., .obj vs .OBJ). That might be something to look at if your problem persists.

**Comment by 1Ruby** [comment]
Same issue on Ubuntu. According to this [comment](https://github.com/google-deepmind/mujoco/issues/1685#issuecomment-2208865258) the reason is the limit in the number of open file descriptors. I tried `ulimit -n 10000` and solved it.
