### ISSUE TITLE
[Bug] Image rander of right_eye.

### ISSUE THREAD

**Issue by Xianqi-Zhang** [carlosferrazza/humanoid-bench#16]
Hi,
Thanks for your sharing.
I would like to report a  bug.

The camera_name of right eye should be "right_eye_camera".
https://github.com/carlosferrazza/humanoid-bench/blob/3951d65bc85e16a562d091a7f4820150c20ed91f/humanoid_bench/wrappers.py#L545-L552

Best regards.

**Comment by carlosferrazza** [comment]
Thanks for pointing this out, fixed in the latest version.
