### ISSUE TITLE
Do Authors release pretrained checkpoints for all tasks?

### ISSUE THREAD

**Issue by rl-max** [carlosferrazza/humanoid-bench#22]
Hi, thank you for the nice work and I think it has helped me a lot for experimenting with humanoid robots! 

Have you guys also released the pretrained checkpoints (eg., TD-MPC for all the tasks including manipulation and locomotions)?

**Comment by Subuday** [comment]
Same here search pertaining checkpoints for TD-MPC2.

**Comment by carlosferrazza** [comment]
Hi, and thanks for the interest in our work! We do not provide TD-MPC2 checkpoints, but if you are interested in comparing with our results without rerunning the jobs, we have released all learning curves, see here: https://github.com/carlosferrazza/humanoid-bench?tab=readme-ov-file#paper-training-curves
