### ISSUE TITLE
Visualization rendering frame rate issues

### ISSUE THREAD

**Issue by fangkaipeng** [carlosferrazza/humanoid-bench#23]
Hi, I'm using MobaXterm SSH to connect to the server. While doing Test Environments, I noticed that the rendering's FPS is very low (only around 1-2) and that the server is not calling the GPU but is using a lot of CPU for rendering. Can we speed up the rendering?

**Comment by carlosferrazza** [comment]
Hi! Is your server running Ubuntu? Have you tried adding `MUJOCO_GL='egl'`?

**Comment by fangkaipeng** [comment]
Yes, it works! Thank you (I am a layman).
