### ISSUE TITLE
how to change Shadow hand to unitree hand

### ISSUE THREAD

**Issue by bethalageetachandraraju** [carlosferrazza/humanoid-bench#24]
How to change H1 robot hand from default shadow hand to unitree hand.

**Comment by carlosferrazza** [comment]
We just added an example environment to do that. Try running the task `h1simplehand-stand-v0`. To extend this for other tasks, you should just create/adapt the corresponding xml, e.g. [this](https://github.com/carlosferrazza/humanoid-bench/blob/main/humanoid_bench/assets/envs/h1simplehand_pos_stand.xml). Let me know if you run into any issues!
