### ISSUE TITLE
Resource not found

### ISSUE THREAD

**Issue by K-Humanoid** [carlosferrazza/humanoid-bench#4]
Thx for your awesome work!

I'm able to test environments. 
But when i try to change observations, i encounter this error:  **ValueError: Error: resource not found via provider or OS filesystem: '/home/kh/Documents/humanoid-bench/humanoid_bench/assets/envs/../shadow_hand_submodel/assets/forearm_0.obj'**

I checked the path, which is correct, and the obj exists. 

Any clues on that will be appreciated. Thx!

**Comment by carlosferrazza** [comment]
Hi! Could you provide more details on the exact command you are running?

**Comment by Bailey-24** [comment]
hi, i'm curious about why you didn't use vision input, it is difficult to use?
such as keep the root fixed or follow the given speed，and then the humanoid use vision input to pick and place some object.

**Comment by K-Humanoid** [comment]
> Hi! Could you provide more details on the exact command you are running?

Thx for the reply! 

This command  : **python -m humanoid_bench.test_env --env h1touch-stand-v0 --obs_wrapper True --sensors "proprio,image,tactile"**

**Comment by carlosferrazza** [comment]
@Bailey-24 It is definitely possible to use the visual input, but we only benchmarked state-based RL as the required compute budget for vision-based RL generally tends to be much larger!

**Comment by carlosferrazza** [comment]
@K-Humanoid the command runs fine for me (on Mac). Could you try cloning the repo again, and attempt that again? Some users have reported that on some OS there might be issues with the capitalization of the asset files (e.g., .obj vs .OBJ). That might be something to look at if your problem persists.
