### ISSUE TITLE
Large RAM usage when using PPO for training

### ISSUE THREAD

**Issue by OliEfr** [carlosferrazza/humanoid-bench#5]
When using ppo for training with multiple `num_envs`, the RAM usage explodes. For instance, for 12 envs I need around 35GB RAM, for 8 envs about 25GB. I have this issues on multiple independent install of `humanoid-bench` on different machines. I also tested it with TD3 from stable-baselines3 and the same issue occured.

I assume it is an issue with the environments, as I didn't experience this issue with other stable-baselines3 projects. I didn't check how it is for the other algorithms implemented.

Do you experience the same RAM usages for this project?

**Comment by yinkangning0124** [comment]
> When using ppo for training with multiple `num_envs`, the RAM usage explodes. For instance, for 12 envs I need around 35GB RAM, for 8 envs about 25GB. I have this issues on multiple independent install of `humanoid-bench` on different machines. I also tested it with TD3 from stable-baselines3 and the same issue occured.
> 
> I assume it is an issue with the environments, as I didn't experience this issue with other stable-baselines3 projects. I didn't check how it is for the other algorithms implemented.
> 
> Do you experience the same RAM usages for this project?

Hi, I also faced such problem, have you solved it ?

**Comment by OliEfr** [comment]
No, it might be inherent to the envs. One could try to alter the env-xml-files to determine the cause. Or try using a different TD3/PPO implemention than SB3 to see if it's an issue with that.

**Comment by carlosferrazza** [comment]
@OliEfr @yinkangning0124 could you send me the command to reproduce the RAM usage you mention? I have been testing state-based PPO on `h1hand-walk-v0` and it seems to take less than 10GB RAM both on Mac and Ubuntu with 12 envs, and it scales pretty much linearly with the number of envs.
