### ISSUE TITLE
Visualization artifact for `test_env`

### ISSUE THREAD

**Issue by Jiayuan-Gu** [carlosferrazza/humanoid-bench#6]
When I run `python -m humanoid_bench.test_env --env h1hand-walk-v0`, the viewer will show black screen after a few epochs. The issue can be fixed by commenting out the env created for offscreen rendering.
Report this issue for future debugging.

---
**Basic information:**
OS: Ubuntu 22.04
Graphic Card: NVIDIA GeForce RTX 4090 (545.29.06)

**Comment by carlosferrazza** [comment]
I could not reproduce on my end, but glad you found a solution by isolating the two rendering envs. Thanks for pointing this out!
