### ISSUE TITLE
Question regarding max train steps for SAC

### ISSUE THREAD

**Issue by godnpeter** [carlosferrazza/humanoid-bench#7]
Hi Carmelo,

Thank you for your great work. I am really enjoying trying out your new humanoid simulator! Really awesome work you have done here. I just have a simple question,

Why is the SAC max_timestep set to 5M in the README? Was SAC trained only for 5M? It seems like SAC was trained with 10M in your paper and your other algorithms like TD-MPC2 seem to work for 10M steps as default. 
At first I though you implemented something like "action repeat" somewhere but I can't find it. 

So, it would be great for me if you could clarify this!

Once again, thank you for your great work and I look forward to hearing back from you!

**Comment by carlosferrazza** [comment]
Thank you for the interest in our work!

You are right, we ran the SAC experiments in the paper for 10M steps. I updated the readme and the SAC default params to make this consistent.
