### ISSUE TITLE
Adding new env - documentation

### ISSUE THREAD

**Issue by budzianowski** [carlosferrazza/humanoid-bench#8]
Hi Carlos, thanks for sharing the benchmark! We would like to run it with our open-source Stompy. 
Do you have some documentation/reading how do go about it?

**Comment by carlosferrazza** [comment]
Hi! Here are some basic instructions to get started:
* Add a new robot class [here](https://github.com/carlosferrazza/humanoid-bench/blob/main/humanoid_bench/robots.py)
* Add your robot to the `ROBOTS` dict [here](https://github.com/carlosferrazza/humanoid-bench/blob/fcb8b29144d009162798bbe4a993f2e7b9c35421/humanoid_bench/env.py#L63)
* Create task xmls that wrap your model, see [this](https://github.com/carlosferrazza/humanoid-bench/blob/main/humanoid_bench/assets/envs/h1_pos_stand.xml) for an example about the H1
* Register your new task [here](https://github.com/carlosferrazza/humanoid-bench/blob/main/humanoid_bench/__init__.py)

Make sure that the task, robot, and control type reflect in the xml name, e.g., the task `stand` for the robot `h1` with position control corresponds to the xml `h1_pos_stand.xml`. See [this line](https://github.com/carlosferrazza/humanoid-bench/blob/fcb8b29144d009162798bbe4a993f2e7b9c35421/humanoid_bench/env.py#L121) for details on how the gymnasium handle is generated.

Hope this helps! Feel free to open a PR if you'd like to include your robot in the benchmark.
